Repository codeitbijay/Hacktoberfest2k20, pull requests merged in 2020-10, with the labels that each got.

#29 hello world in awk
  hello_world.awk
Labels: Hacktoberfeast-accepted

#30 armstrong
  armstrong
Labels: Hacktoberfeast, Hacktoberfeast-accepted, documentation, good first issue

#31 towerOfHanoi
  C++/towerOfHanoi.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, enhancement, good first issue

#33 A Dynamic Programming Question. Plz Add a hacktoberfest label to it.
  C++/Subset_Sum_Problem.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#34 Create sum in C
  sum in C
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation

#35 Added code for postfix to infix conversion in C++
  C++/post_infix.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#32 Create palindrome_string.py
  Python/palindrome_string.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#36 Added Recursion
  C++/Recurssion/Q-REC_Subsequences.cpp
  C++/Recurssion/REC_Duplicate.cpp
  C++/Recurssion/REC_Encoding.cpp
  C++/Recurssion/REC_Flood_Fill.cpp
  C++/Recurssion/REC_Knight_tour.cpp
  C++/Recurssion/REC_Ladder.cpp
  C++/Recurssion/REC_Ladder_2.cpp
  C++/Recurssion/REC_Last_Occurance.cpp
  C++/Recurssion/REC_Maze_Path.cpp
  C++/Recurssion/REC_Merge_Sort.cpp
  C++/Recurssion/REC_NQueens.cpp
  C++/Recurssion/REC_OCCURANCES.cpp
  C++/Recurssion/REC_Print_Zigzag.cpp
  C++/Recurssion/REC_String_Compression.cpp
  C++/Recurssion/REC_Strings_Remove_Duplicates.cpp
  C++/Recurssion/REC_Target_Sum.cpp
  C++/Recurssion/REC_Tower_Of_Hanoi.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest

#37 Create hello_world.jl
  hello_world.jl
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#38 Sacks and Queues
  C++/Stack and Queue/Balanced_Brackets.cpp
  C++/Stack and Queue/Duplicate_Brackets.cpp
  C++/Stack and Queue/Infix_Evaluation.cpp
  C++/Stack and Queue/Next-Greater_Element_To_The_Right.cpp
  C++/Stack and Queue/Smallest_Number_Following_Pattern.cpp
  C++/Stack and Queue/Stock_Span.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#39 Linear search in python
  Python/python-linear-search.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest

#40 Add files via upload
  Angular work Flow.md
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#41 Checking for anagram
  Anagram.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#42 Quicksort in Ruby
  quicksort.rb
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#43 Added CPF validation class in PHP.
  PHP/validate_cpf.php
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#44 Added hamming code calculator
  Python/hamming.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#45 Create shippingCalc.py
  Python/shippingCalc.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#46 Add dp coin change solution in js
  javascript/dynamic programming/coin_change.js
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement, good first issue

#47 Add nth fibonacci number in javascript
  javascript/dynamic programming/fibonacci.js
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#48 Minesweeper
  Minesweeper
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#49 Move files and create folders , edit README
  C/Caesar cipher Decryption code using C
  C/Pulse_Amplitude_Modulation.m
  C/Stack using array code in C
  C/Towers of Hanoi code in c
  C/sum in C
  PHP/calculate_the_area_of_the_circle.php
  PHP/circumference.php
  Python/Email bot.py
  Python/quicksort.py
  Python/sanke water gun game.py
  README.md
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#50 added Largest Number of an Array C++ Program
  C++/Largest Number of an Array.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#53 Create Product_Of_Array_Except_Self.cpp
  C++/Product_Of_Array_Except_Self.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#51 heaps STL
  C++/Heaps with STL/K_Largest_Elements.cpp
  C++/Heaps with STL/Sort_K_sorted_Array.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#55 Added Bubble sort algorithm in java
  Java/bubblesort.java
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#54 Add Caesar Encryption Program
  Python/caesar.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement, good first issue

#56 added bubble sort using python
  Python/BubbleSort.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement, good first issue

#57 Add python code for Tower of Hanoi problem
  Python/TowerOfHanoi.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#58 Create decimal_to_binary_Scientist69.cpp
  decimal_to_binary_Scientist69.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement, good first issue

#59 added new basic typing test in javascript
  javascript/TypingTest/bg.jpg
  javascript/TypingTest/index.html
  javascript/TypingTest/main.css
  javascript/TypingTest/script.js
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement, good first issue

#60 added simple react app
  Photography_react_app/README.md
  Photography_react_app/package-lock.json
  Photography_react_app/package.json
  Photography_react_app/public/favicon.ico
  Photography_react_app/public/index.html
  Photography_react_app/public/logo192.png
  Photography_react_app/public/logo512.png
  Photography_react_app/public/manifest.json
  Photography_react_app/public/robots.txt
  Photography_react_app/src/App.css
  Photography_react_app/src/App.js
  Photography_react_app/src/App.test.js
  Photography_react_app/src/assets/bg.jpg
  Photography_react_app/src/assets/close.png
  Photography_react_app/src/assets/facebook.png
  Photography_react_app/src/assets/instagram.png
  Photography_react_app/src/assets/joker.png
  Photography_react_app/src/assets/logo.png
  Photography_react_app/src/assets/logo1.png
  Photography_react_app/src/assets/play.png
  Photography_react_app/src/assets/toggle.png
  Photography_react_app/src/assets/twitter.png
  Photography_react_app/src/diamond.js
  Photography_react_app/src/diamond/diamonds.css
  Photography_react_app/src/diamond/jquery.diamonds.js
  Photography_react_app/src/flip.js
  Photography_react_app/src/flipimg/logo.png
  Photography_react_app/src/index.css
  Photography_react_app/src/index.js
  Photography_react_app/src/logo.svg
  Photography_react_app/src/serviceWorker.js
  Photography_react_app/src/setupTests.js
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement, good first issue

#61 Create Bucket_SOrt.cpp
  C++/Bucket_SOrt.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#62 Create keylogger.py
  Python/keylogger.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#64 Create hello_world.r
  hello_world.r
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement

#63 Create paster.py
  Python/paster.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement, good first issue

#65 add algorithm
  C/Bankers Algorithm/bankersAlgorithm.c
  C/Binary-Recursion-search/binaryRecursionSearch.c
  C/Command Simulation (cp)/cp.c
  C/Command Simulation (grep)/grep.c
  C/Command Simulation (ls)/ls.c
  C/Command Simulation (rm)/rm.c
  C/Counting Sort/countingSort.c
  C/Factorial/factorial.c
  C/Fibonacci Series/FibonacciSeries.c
  C/Matrix (difference)/difference.c
  C/Matrix (display)/display.c
  C/Matrix (multiplication)/multiplication.c
  C/Matrix (scaler multiplication)/scalerMultiplication.c
  C/Matrix (sum)/sum.c
  C/Matrix (transpose)/transpose.c
  C/Merge Sort/mergeSort.c
  C/Pascal's Triangle/pascalsTriangle.c
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement

#66 Landing Web Page
  Web Design Project/HP.css
  Web Design Project/HP.html
  Web Design Project/images/camera.jpg
  Web Design Project/images/intro-bg_1.jpg
  Web Design Project/images/shirt.jpg
  Web Design Project/images/watch.jpg
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#67 Add Vigenere Encryption Program
  Python/shiftVigenere.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#68 Create MinMax.java
  Java/MinMax.java
  Java/Palindrome.java
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement

#69 Polynomial Addition in C
  C/polynomial_addition.c
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement, good first issue

#70 Create PrimeNumbers.java
  Java/PrimeNumbers.java
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation

#72 Added 3 files in C++
  C++/Diameter_Of_Tree.cpp
  C++/Recurssion/REC_Soduko.cpp
  C++/Shortest_Common_Superstring.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement

#73 Create to_roman.py
  Python/to_roman.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement

#74 n queen
  C/nqueen.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement, good first issue

#71 Create fibonacci.java
  Java/fibonacci.java
  Java/kadaneAlgorithm.java
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement, good first issue

#75 Add project to show how to assemble the fibonacci sequence in C#
  .gitignore
  CSharp/.gitignore
  CSharp/Fibonacci/Fibonacci.sln
  CSharp/Fibonacci/Fibonacci/Fibonacci.csproj
  CSharp/Fibonacci/Fibonacci/Program.cs
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement, good first issue

#76 Create LCS.java
  Java/LCS.java
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement, good first issue

#78 Vector Permutation Encryption Program
  Python/vectorPerm.py
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement

#79 Added Backtracking example with NQueens Problem
  C++/Backtracking.cpp
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement

#80 Code to reverse a string using Stack
  C/reverse_string_stack.c
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, documentation, enhancement

#81 Grant/add farm challenge https://edabit.com/challenge/4AaTbg5NuA8eSijcr
  CSharp/TotalLegsOnAFarm/TotalLegsOnAFarm.sln
  CSharp/TotalLegsOnAFarm/TotalLegsOnAFarm/Program.cs
  CSharp/TotalLegsOnAFarm/TotalLegsOnAFarm/TotalLegsOnAFarm.csproj
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement, good first issue

#82 reverse array
  javascript/reverse array/reverse.js
Labels: Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest, enhancement, good first issue

#84 MergeSort with timeit library to calculate runtime
  Python/MergeSort.py
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, hacktoberfest-accepted

#85 Add Myself
  javascript/toFixed.js
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#86 Grant/add api example for dotnet core and C#
  CSharp/Example.API/Example.API.sln
  CSharp/Example.API/Example.API/Controllers/WeatherForecastController.cs
  CSharp/Example.API/Example.API/Example.API.csproj
  CSharp/Example.API/Example.API/Program.cs
  CSharp/Example.API/Example.API/Properties/launchSettings.json
  CSharp/Example.API/Example.API/Startup.cs
  CSharp/Example.API/Example.API/WeatherForecast.cs
  CSharp/Example.API/Example.API/appsettings.Development.json
  CSharp/Example.API/Example.API/appsettings.json
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#87 0-1 Knapsack Memoization & Tabulation
  C++/01knapsack.cpp
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#88 Create print_reverse_number_Scientist69.cpp
  print_reverse_number_Scientist69.cpp
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#83 cut array
  javascript/cut array/cut.js
Labels: Hacktoberfeast, Hacktoberfest, documentation, duplicate, enhancement, good first issue, hacktoberfest-accepted

#89 Add basic solution for tsp
  CSharp/TravelingSalesmen/TravelingSalesmen.sln
  CSharp/TravelingSalesmen/TravelingSalesmen/City.cs
  CSharp/TravelingSalesmen/TravelingSalesmen/Program.cs
  CSharp/TravelingSalesmen/TravelingSalesmen/Stop.cs
  CSharp/TravelingSalesmen/TravelingSalesmen/Tour.cs
  CSharp/TravelingSalesmen/TravelingSalesmen/TravelingSalesmen.csproj
Labels: Hacktoberfeast, Hacktoberfest, documentation, good first issue, hacktoberfest-accepted

#90 Bellman Ford Algorithm
  C++/Bellman Ford.cpp
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#91 Checking Anagrams in java
  Java/Anagrams.java
Labels: Hacktoberfeast, Hacktoberfest, documentation, duplicate, enhancement, good first issue, hacktoberfest-accepted

#92 Dijkstra's Algo in C++
  C++/Dijkstaras Algo.cpp
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, hacktoberfest-accepted

#94 Create a Maximum path sum in a triangle
  Maximum_path_sum_in_a_triangle.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#95 Huffman Coding in C++
  C++/Huffman Coding.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#96 Reverse Linked List with and without Recursion
  C++/Reverse LL using Recursion.cpp
  C++/Reverse LL without Recursion.cpp
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#97 add sortComparison.py
  Python/sortComparison.py
Labels: Hacktoberfeast, Hacktoberfest, hacktoberfest-accepted

#98 Create Knapsack.java
  Java/Knapsack.java
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#99 added Exponential Search in Js
  javascript/Searches/Exponential Search.js
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, hacktoberfest-accepted

#93 GCD Code Added
  C++/gcd.cpp
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#100 adding a scraper
  Python/slideshareScraper.py
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, hacktoberfest-accepted

#101 MIN-MAX USING THE DESIGN AND CONQUER STRATEGY
  C/MIN-MAX/main.c
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, hacktoberfest-accepted

#102 game landing page
  LandingPageGame/css/style.css
  LandingPageGame/css/utilities.css
  LandingPageGame/header/1.jpg
  LandingPageGame/header/2.jpg
  LandingPageGame/header/3.jpg
  LandingPageGame/header/4.jpg
  LandingPageGame/header/5.jpg
  LandingPageGame/header/6.jpg
  LandingPageGame/header/7.jpg
  LandingPageGame/header/8.jpg
  LandingPageGame/header/BG.jpg
  LandingPageGame/header/Screenshot 2020-05-18 at 11.05.53 PM (1).png
  LandingPageGame/header/Screenshot 2020-05-18 at 11.05.53 PM.png
  LandingPageGame/home.html
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, hacktoberfest-accepted, help wanted

#103 Heapsort added
  Java/heapsort.java
Labels: Hacktoberfeast, documentation, enhancement, good first issue

#104 I hope you like this one
  Python/dictionary.py
  dictionary.py
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, hacktoberfest-accepted

#105 Update factorial.c
  C/Factorial/factorial.c
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#106 Add new language and knn algorithm
  R/dwnn.r
  R/knn2.r
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted, help wanted

#107 add image convolution script
  Python/imageConvolution.py
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#108 added fat-file-system simulations
  C++/FAT-improved.cpp
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted, help wanted

#109 Add Tic Tac Toe program in Java
  Java/tic_tac_toe/Main.java
  Java/tic_tac_toe/TACTIC.java
Labels: Hacktoberfeast, Hacktoberfest, documentation, good first issue, hacktoberfest-accepted, help wanted

#182 Added Kalkulator JS
  javascript/Kalkulator/index.html
  javascript/Kalkulator/js.js
  javascript/Kalkulator/style.css
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#183 Revert "Added calculator JS"
  javascript/Kalkulator/index.html
  javascript/Kalkulator/js.js
  javascript/Kalkulator/style.css
Labels: Hacktoberfeast, Hacktoberfest, good first issue, hacktoberfest-accepted

#181 Snake water game
  Python/Snake water game.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#180 Create quicksort_ahnaf.c
  C/quicksort_ahnaf.c
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#179 Create k knight
  k knight
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#178 Added recursive and iterative way to calculate Fibonacci series in PHP.
  PHP/fibonacci.php
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#177 Add helloworld.c
  C/helloworld.c
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#176 Create Bitmask.cpp
  C++/Bitmask.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#175 length of longest palindrome substring.
  C++/Recurssion/longPalindromeSubstring.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#174 hacktoberfest-accepted
  LCMwithoutgcd.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#173 added download manager script
  Python/Dmanager.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#172 Create Prim's algorithm
  C++/Prims_Algorithm.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#171 added program to add 2 large numbers
  C++/addLargeNo.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#170 snake script
  Python/snake.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#169 Added Group anagrams
  C++/permutations.cpp
  Java/Group anagrams.java
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#168 Create SimpleCalculator2.py
  Python/SimpleCalculator2.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#167 organizing files in folders
  AWK/hello_world.awk
  C++/Maximum_path_sum_in_a_triangle.cpp
  C++/decimal_to_binary_Scientist69.cpp
  C++/print_reverse_number_Scientist69.cpp
  Julia/hello_world.jl
  Python/Anagram.py
  R/hello_world.r
  Ruby/quicksort.rb
  dictionary.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#166 Added a simple game of scissors paper rock in python
  Python/scissorsPaperRock.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#165 Created a basic program to calculate Simple Interest.
  Python/SimpleInterest.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#164 Create char_removal_from_string.py
  Python/char_removal_from_string.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#163 hacktoberfest2k20
  C++/floydWarshals.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#162 added prime number checking code
  C/PrimeNumberCheck/CheckPrimeNumbers.c
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#161 Add simpleMaths
  Python/simpleMaths.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#160 Added BinarySearch.java
  Java/BinarySearch.java
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#159 added movie recommender program along with datasets
  Python/Movie Recommender System/Collaborative_filtering.py
  Python/Movie Recommender System/links.csv
  Python/Movie Recommender System/movies.csv
  Python/Movie Recommender System/ratings.csv
  Python/Movie Recommender System/tags.csv
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#158 gets the 100 most used french verbs from a website
  Python/get100.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#157 Create VeryBigSum.cpp
  C++/VeryBigSum.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#156 Heap_Sort in Python added
  Python/Heap_Sort.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#155 Create linkedlist.cpp
  C++/linkedlist.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#154 Adding cleanup merged branch
  Shell/artifactory-cleanup.sh
  Shell/cleanup-merged-branch.sh
  Shell/deply-file.sh
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#150 Tower Of Hanoi using C Language
  Tower_Of_Hanoi.C
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#148 Added Web Design Project
  Web Design Project/Random-Hex-Generator/css/bootstrap.min.css
  Web Design Project/Random-Hex-Generator/css/main.css
  Web Design Project/Random-Hex-Generator/index.html
  Web Design Project/Random-Hex-Generator/js/all.js
  Web Design Project/Random-Hex-Generator/js/app.js
  Web Design Project/Random-Hex-Generator/js/bootstrap.bundle.min.js
  Web Design Project/Random-Hex-Generator/js/jquery-3.3.1.min.js
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#147 Adding GFG Competetive Coding Questions for Hacktoberfest 2020
  C++/DistinctAbsoluteArrayEle.cpp
  C++/searchRotated.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#146 Using js inbuilt reverse function
  javascript/reverse array/reverse.js
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#145 added 3 programs in javascript: caesars cipher; roman numeral converter; telephone number validator
  javascript/caesars-cipher.txt
  javascript/roman-numeral-converter.txt
  javascript/telephone-number-validator.txt
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#143 added code for merging k sorted linked lists
  C++/merge-k-sorted-lists.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#141 Create Donut.vue
  javascript/Donut.vue
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#140 Create StaticTrie.cpp
  C++/StaticTrie.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#139 Passing on from others
  Python/hello.py
  perl/dice.pl
  perl/hello-world.pl
  perl/toRoman.pl
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#138 Create ASCIIPrinting.java
  Java/ASCIIPrinting.java
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#137 Updates done adding new programs to C++ & Python
  C++/JollyJumper.cpp
  C++/findMinDiff.cpp
  C++/imakshat47_complexSorting copy.cpp
  C++/imakshat47_complexSorting.cpp
  C++/imakshat47_mapsQuery.cpp
  C++/imakshat47_maxElement.cpp
  C++/imakshat47_stlSets.cpp
  C++/imakshat47_vectorDynamicErase.cpp
  C++/imakshat47_vectorLowerBound.cpp
  C++/imakshat47_vectorSort.cpp
  C++/maxElement_imakshat47.cpp
  C++/removeSort.cpp
  C++/sorting_imakshat47.cpp
  C++/vectorErase_imakshat47.cpp
  C++/vectorSort_imakshat47.cpp
  C++/xorArray.cpp
  Python/Chacha!!OChacha.py
  Python/JadooAndDNATranscription.py
  Python/JadooHatesNumbers.py
  Python/JadooVsKoba.py
  Python/ReasonsWhy.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#136 Create strongNumber.c
  C/strongNumber.c
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#135 added basicRAT python asthac
  Python/basicRAT.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#134 Create HelloWorld.java
  Java/HelloWorld.java
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#132 added quicksort.py
  Python/quicksort.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#131 Added Z Algorithm and Mo's Algorithm
  C++/Mo's Algorithm.cpp
  C++/Z Algorithm.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#130 adding core HTML
  Advance HTML/rate.html
  C++/Stack and Queue/BFS_traversal.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#129 Added URL encode decode utility function example in csharp .
  CSharp/URLEncodeDecode/URLEncodeDecode.sln
  CSharp/URLEncodeDecode/URLEncodeDecode/Program.cs
  CSharp/URLEncodeDecode/URLEncodeDecode/QueryParameter.cs
  CSharp/URLEncodeDecode/URLEncodeDecode/URLEncodeDecode.csproj
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#128 add addClassOnScroll Library to javascript
  javascript/addClassOnScroll/README.md
  javascript/addClassOnScroll/add-class-on-scroll.js
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#225 balanced_parentheses_by_using_Stacks
  C++/balanced_parentheses_by_using_Stacks.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#224 Create coinchangecombination.cpp
  C++/coinchangecombination.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#223 Added SinglyLinkedList.java via upload
  Java/SinglyLinkedList.java
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#222 Create min-max-avg.c
  C/X.c
  C/min-max-avg.c
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#221 Create geekaditi-longest-common-subsequence-CPP.cpp
  C++/geekaditi-longest-common-subsequence-CPP.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#220 Create queue.cpp
  C++/Stack and Queue/queue.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#219 added Interpolation search
  javascript/Searches/interpolationSearch.js
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#218 Added Insertion_Sort.c
  C/Bubble_Sort.c
  Java/Arithmetic_Progression.java
  Java/GCD.java
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#214 Added Arithmetic_Progression.java
  Java/GCD.java
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#213 Added GCD.java
  Java/GCD.java
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#382 Updated Binary Search.cpp
  C++/Binary Search.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, hacktoberfest-accepted

#380 SparseMatrix
  C++/sparse1.cpp
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#381 Create InterestCalculator.java
  CSharp/WaterWalls.cs
  Java/InterestCalculator.java
Labels: Hacktoberfeast, Hacktoberfest, documentation, enhancement, good first issue, hacktoberfest-accepted

#379 Update rate.html
  Advance HTML/rate.html
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#378 add init rust code
  Rust/init/Cargo.toml
  Rust/init/src/main.rs
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#377 Added Hangman in python
  Python/Hangman.py
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#374 3d array
  3D array
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#376 Added Three C++ Programs Related to Patterns
  C++/Inverted half pyramid using numbers.cpp
  C++/Program to print half pyramid using alphabets.cpp
  C++/Programs to display pyramid and inverted pyramid using * and digits.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#375 Added Operators in C++
  C++/operators/bitwiseAND.cpp
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#373 Create Travelling Salesman
  C++/Travelling Salesman
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#372 Create BoxStacking
  C++/BoxStacking
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted

#370 Create NQueens
  C++/NQueens
Labels: Hacktoberfeast, Hacktoberfest, enhancement, good first issue, hacktoberfest-accepted
